language: cpp
compiler:
- clang
- gcc
script:
- CMake .
- CPack .
- CMake --build .
- CMake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -Zhanbek:$BINTRAY_API_KEY "https://api.bintray.com/content/Zhanbek/OTUS_Homework/Homework_01/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

